export default {
    testEnvironment: "node",
    transform: {},
    moduleFileExtensions: ["js", "mjs"],
    testMatch: ["**/tests/**/*.test.js", "**/tests/**/*.test.mjs"],
    verbose: true,
    forceExit: true,
    clearMocks: true,
    resetMocks: true,
    restoreMocks: true,
    testTimeout: 30000,
    setupFilesAfterEnv: ["./tests/setup.js"],
    collectCoverageFrom: [
        "src/**/*.js",
        "!src/index.js",
        "!src/db/index.js",
    ],
    coverageDirectory: "coverage",
    coverageReporters: ["text", "lcov", "html"],
};
